### ISSUE TITLE
The first expandable hint text requires two clicks 

### ISSUE THREAD

**Issue by pierrekhouryy** [thomhurst/ExpandableHintText#2]
I use this library in my app, and I am facing this issue which is also present on the demo app of this library. the first view of the bunch seems to be in a weird state when the activity first loads. therefore it requires two clicks to start registering input in this view. Is this an issue or is it simply the way these views function ?[
<img width="416" alt="Screen Shot 2019-10-01 at 4 12 58 PM" src="https://user-images.githubusercontent.com/48325025/65965067-a787c200-e466-11e9-96e8-67d982edfc34.png">
](url)

**Comment by thomhurst** [comment]
@pierrekhouryy Hmm.. I can't replicate this. It starts taking input after 1 press for me. What device / OS version are you using?

**Comment by thomhurst** [comment]
Closing as can't replicate and receiving no further information.
